"""'sync_schema_for_audit_and_transitions'

Revision ID: c97868e77dbe
Revises: c9b3138cca13
Create Date: 2026-01-25 04:29:02.797708+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97868e77dbe'
down_revision = 'c9b3138cca13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'workflow_requests', ['request_id'], ['id'], ondelete='SET NULL')
    op.add_column('step_transitions', sa.Column('outcome', sa.String(length=50), nullable=False))
    op.alter_column('step_transitions', 'to_step_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step_transitions', 'to_step_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('step_transitions', 'outcome')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'request_id')
    # ### end Alembic commands ###
