"""Initial schema

Revision ID: c9b3138cca13
Revises: 
Create Date: 2026-01-23 14:46:24.032932+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9b3138cca13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_is_active'), 'workflows', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=True)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_role_id', sa.UUID(), nullable=True),
    sa.Column('required_permission_id', sa.UUID(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('is_conditional', sa.Boolean(), nullable=False),
    sa.Column('condition_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['required_permission_id'], ['permissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['required_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('step_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_step_id', sa.UUID(), nullable=False),
    sa.Column('to_step_id', sa.UUID(), nullable=False),
    sa.Column('condition_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['from_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_transitions_from_step_id'), 'step_transitions', ['from_step_id'], unique=False)
    op.create_index(op.f('ix_step_transitions_id'), 'step_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_step_transitions_to_step_id'), 'step_transitions', ['to_step_id'], unique=False)
    op.create_table('workflow_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=True),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'ESCALATED', name='requeststatus'), nullable=False),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_step_id'], ['workflow_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_requests_id'), 'workflow_requests', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_requests_requester_id'), 'workflow_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_workflow_requests_status'), 'workflow_requests', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_requests_workflow_id'), 'workflow_requests', ['workflow_id'], unique=False)
    op.create_table('request_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'ESCALATED', name='requeststatus'), nullable=True),
    sa.Column('to_status', sa.Enum('CREATED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'ESCALATED', name='requeststatus'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['workflow_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_state_history_changed_at'), 'request_state_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_request_state_history_id'), 'request_state_history', ['id'], unique=False)
    op.create_index(op.f('ix_request_state_history_request_id'), 'request_state_history', ['request_id'], unique=False)
    op.create_table('request_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decision_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['workflow_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_steps_assigned_to'), 'request_steps', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_request_steps_deadline'), 'request_steps', ['deadline'], unique=False)
    op.create_index(op.f('ix_request_steps_id'), 'request_steps', ['id'], unique=False)
    op.create_index(op.f('ix_request_steps_is_sla_breached'), 'request_steps', ['is_sla_breached'], unique=False)
    op.create_index(op.f('ix_request_steps_request_id'), 'request_steps', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_steps_status'), 'request_steps', ['status'], unique=False)
    op.create_index(op.f('ix_request_steps_step_id'), 'request_steps', ['step_id'], unique=False)
    op.create_table('sla_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_step_id', sa.UUID(), nullable=False),
    sa.Column('escalated_to', sa.UUID(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_step_id'], ['request_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_escalations_escalated_at'), 'sla_escalations', ['escalated_at'], unique=False)
    op.create_index(op.f('ix_sla_escalations_escalated_to'), 'sla_escalations', ['escalated_to'], unique=False)
    op.create_index(op.f('ix_sla_escalations_id'), 'sla_escalations', ['id'], unique=False)
    op.create_index(op.f('ix_sla_escalations_request_step_id'), 'sla_escalations', ['request_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_escalations_request_step_id'), table_name='sla_escalations')
    op.drop_index(op.f('ix_sla_escalations_id'), table_name='sla_escalations')
    op.drop_index(op.f('ix_sla_escalations_escalated_to'), table_name='sla_escalations')
    op.drop_index(op.f('ix_sla_escalations_escalated_at'), table_name='sla_escalations')
    op.drop_table('sla_escalations')
    op.drop_index(op.f('ix_request_steps_step_id'), table_name='request_steps')
    op.drop_index(op.f('ix_request_steps_status'), table_name='request_steps')
    op.drop_index(op.f('ix_request_steps_request_id'), table_name='request_steps')
    op.drop_index(op.f('ix_request_steps_is_sla_breached'), table_name='request_steps')
    op.drop_index(op.f('ix_request_steps_id'), table_name='request_steps')
    op.drop_index(op.f('ix_request_steps_deadline'), table_name='request_steps')
    op.drop_index(op.f('ix_request_steps_assigned_to'), table_name='request_steps')
    op.drop_table('request_steps')
    op.drop_index(op.f('ix_request_state_history_request_id'), table_name='request_state_history')
    op.drop_index(op.f('ix_request_state_history_id'), table_name='request_state_history')
    op.drop_index(op.f('ix_request_state_history_changed_at'), table_name='request_state_history')
    op.drop_table('request_state_history')
    op.drop_index(op.f('ix_workflow_requests_workflow_id'), table_name='workflow_requests')
    op.drop_index(op.f('ix_workflow_requests_status'), table_name='workflow_requests')
    op.drop_index(op.f('ix_workflow_requests_requester_id'), table_name='workflow_requests')
    op.drop_index(op.f('ix_workflow_requests_id'), table_name='workflow_requests')
    op.drop_table('workflow_requests')
    op.drop_index(op.f('ix_step_transitions_to_step_id'), table_name='step_transitions')
    op.drop_index(op.f('ix_step_transitions_id'), table_name='step_transitions')
    op.drop_index(op.f('ix_step_transitions_from_step_id'), table_name='step_transitions')
    op.drop_table('step_transitions')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_is_active'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
